# Define the goal
#full path to the input bag that has atleast camera_info and image messages
string bag_file_name
#full path to the desired output file. jpg or png extension required
string stitch_file_name
---
# Define the result
int32 result_flags
int32 PANO_SUCCESS=1
---
# Define a feedback message
float32 percent_complete